"""maatml report: regenerated byte-identically from the records alone."""

from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from maatml.cli import app
from maatml.evaluation.harness import Report
from maatml.evaluation.stats import wilson_lower
from maatml.report import build_report, render_csv, render_markdown
from maatml.runs import RunRecord

runner = CliRunner()


def _output(tmp_path: Path) -> Path:
    out = tmp_path / "output"
    (out / "eval").mkdir(parents=True)
    (out / "seeds").mkdir()
    records = [
        RunRecord(
            run_id="run-1",
            identity="m@0.1.0",
            architecture="causal_sft",
            status="completed",
            started_at="2026-01-01T00:00:00Z",
            out_dir="/elsewhere/run-1",
            gates={"passed": True, "smoke": False, "results": {}},
            selected_checkpoint="checkpoint-200",
            test_spends=[{"benchmark_sha256": "ab" * 32}],
            environment={"git_sha": "abcdef123456", "packages": {"torch": "2.5"}, "cuda": "12.4"},
        ),
        RunRecord(
            run_id="run-2",
            identity="m@0.1.0",
            architecture="causal_sft",
            status="aborted",
            started_at="2026-01-02T00:00:00Z",
            out_dir="/elsewhere/run-2",
        ),
    ]
    with (out / "runs.jsonl").open("w") as handle:
        for rec in records:
            handle.write(json.dumps(rec.model_dump(mode="json"), sort_keys=True) + "\n")
    Report(
        model_id="m",
        dataset="test.jsonl",
        n=100,
        metrics={"all_layers_pass_rate": 0.9, "output_nonempty_rate": 1.0},
        counts={"all_layers_pass_rate": {"k": 90, "n": 100}},
        slices={"camera": {"G1": {"n": 50, "passed": 45, "pass_rate": 0.9, "pass_rate_w95": 0.79}}},
        pathologies=[{"name": "one_class", "evidence": "e"}],
        extras={"benchmark_version": "bv1"},
        gates={
            "passed": True,
            "smoke": False,
            "benchmark_sha256": "cd" * 32,
            "results": {
                "all_layers_pass_rate": {
                    "minimum": 0.82,
                    "actual": 0.9,
                    "passed": True,
                    "tier": "blocking",
                },
                "slice:camera=G1": {
                    "minimum": 0.7,
                    "actual": 0.9,
                    "passed": True,
                    "tier": "advisory",
                },
            },
        },
        passed=True,
    ).write(out / "eval" / "run-1.json")
    (out / "eval" / "run-1.md").write_text("not json")
    (out / "seeds" / "run-1-x2.json").write_text(
        json.dumps(
            {
                "kind": "maatml.seed_study/1",
                "label": "run-1-x2",
                "seeds": [0, 1],
                "runs": [{"run_id": "run-1"}, {"run_id": "run-1b"}],
                "stats": {"eval_loss": {"mean": 1.0, "sd": 0.1, "min": 0.9, "max": 1.1, "n": 2}},
            }
        )
    )
    return out


def test_report_data_comes_from_the_records_with_floor_derivation(tmp_path: Path) -> None:
    data = build_report(_output(tmp_path))
    assert [r["run_id"] for r in data["runs"]] == ["run-1", "run-2"]
    report = data["reports"][0]
    assert report["file"] == "run-1.json" and report["benchmark_version"] == "bv1"
    rate = next(m for m in report["metrics"] if m["metric"] == "all_layers_pass_rate")
    assert rate["derivation"] == {"k": 90, "n": 100, "w95": wilson_lower(90, 100)}
    assert rate["floor"] == 0.82 and rate["passed"] is True and rate["tier"] == "blocking"
    coverage = next(m for m in report["metrics"] if m["metric"] == "output_nonempty_rate")
    assert coverage["derivation"] is None and coverage["floor"] is None
    assert report["slice_gates"][0]["gate"] == "slice:camera=G1"
    assert data["seed_studies"][0]["stats"]["eval_loss"]["min"] == 0.9


def test_markdown_and_csv_regenerate_byte_identically(tmp_path: Path) -> None:
    out = _output(tmp_path)
    first = render_markdown(build_report(out))
    second = render_markdown(build_report(out))
    assert first == second
    assert (
        "| run-1 | completed | no | pass | checkpoint-200 | 1 | 0 | "
        "git abcdef12 torch 2.5 cuda 12.4 |" in first
    )
    assert (
        f"| all_layers_pass_rate | 0.9000 | 90/100 | {wilson_lower(90, 100):.4f} | "
        "0.8200 | blocking | yes |" in first
    )
    assert "- slice camera=G1: n=50 pass_rate 0.9000 w95 0.7900" in first
    assert "- pathology one_class: e" in first
    assert (
        "## seed study run-1-x2" in first
        and "| eval_loss | 1.0000 | 0.1000 | 0.9000 | 1.1000 |" in first
    )
    assert "benchmark version: `bv1`" in first

    csv_text = render_csv(build_report(out))
    assert csv_text == render_csv(build_report(out))
    lines = csv_text.splitlines()
    assert lines[0] == "report,n,smoke,metric,value,k,n_metric,w95,floor,tier,met"
    assert lines[1].startswith("run-1.json,100,no,all_layers_pass_rate,0.9000,90,100,")


def test_report_reads_only_the_output_dir(tmp_path: Path) -> None:
    out = _output(tmp_path)
    mdir = tmp_path
    (mdir / "model.yml").write_text(
        "name: m\nmodel_id: m\nversion: 0.1.0\narchitecture: causal_sft\n"
        "dataset:\n  seed_samples: datasets/s.jsonl\n"
        "evaluation:\n  gates:\n    all_layers_pass_rate: 0.99\n"
        "training:\n  base_model: x\n"
    )
    result = runner.invoke(app, ["report", str(mdir)])
    assert result.exit_code == 0, result.output
    written = (out / "REPORT.md").read_text()
    assert written == render_markdown(build_report(out))
    # model.yml's floor (0.99) is not what the document says; the report's recorded floor is.
    assert "0.9900" not in written and "0.8200" in written

    result = runner.invoke(app, ["report", str(mdir), "--format", "csv", "--stdout"])
    assert result.exit_code == 0 and result.output.startswith("report,n,smoke,metric")
